# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

variables:

  # Global
  ap_vm_image: ubuntu-20.04

  location: eastus2
  environment: dev
  prefix: sl_class_jamg

  # Azure DevOps
  ado_service_connection_rg: Azure-ARM-$(environment)
  ado_service_connection_aml_ws: Azure-ARM-$(environment)

  # DO NOT TOUCH

  # For pipeline reference
  resource_group: language_$(environment)_rg
  aml_workspace: language_$(environment)_ws

  name_for_registered_model: sample_model_single_label_classification

  endpoint_name: $(prefix)_nlp_$(environment)

  cpu_deployment_name: cpu-test
  cpu_instance_count: 1
  cpu_instance_type: Standard_F8s_v2
  gpu_deployment_name: gpu-test
  triton_deployment_name: triton-test
  