$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline
experiment_name: AzureML-Deploy-Samples
display_name: deploy_azureml_textclassificationsinglelabel

# You can change path to your custom files by registering in Data and use their 'Named asset URI' below
inputs:
  # dataset files
  # There are several ways to provide file, if its a data in
  # azureml:<<datasetname>>@latest or azureml:<<datasetname>>:<<version>>
  # azureml://subscriptions/<<subscriptionname>>/resourcegroups/<<resourcegroupname>>/workspaces/<<workspacename>>/datastores/workspaceblobstore/paths/PATH
  cpu_deployment_name: cpu-test
  name_for_registered_model: sample_model_single_label_classification
  endpoint_name: sl-class-jamg-nlp-dev
  cpu_instance_type: Standard_F8s_v2
  cpu_instance_count: 1
  apply_ort: "false"
  apply_deepspeed: "false"

jobs:
  deploy:
    type: command
    component: ../code/components/deploy_model.yaml
    compute: sample-managed-id-cluster
    inputs:
      name_for_registered_model: ${{parent.inputs.name_for_registered_model}}
      endpoint_name: ${{parent.inputs.endpoint_name}}
      instance_type: ${{parent.inputs.cpu_instance_type}}
      instance_count: ${{parent.inputs.cpu_instance_count}}
      deployment_name: ${{parent.inputs.cpu_deployment_name}}