$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline
experiment_name: AzureML-Deploy-Samples
display_name: deploy_azureml_textclassificationsinglelabel

# You can change path to your custom files by registering in Data and use their 'Named asset URI' below
inputs:
  # dataset files
  # There are several ways to provide file, if its a data in
  # azureml:<<datasetname>>@latest or azureml:<<datasetname>>:<<version>>
  # azureml://subscriptions/<<subscriptionname>>/resourcegroups/<<resourcegroupname>>/workspaces/<<workspacename>>/datastores/workspaceblobstore/paths/PATH
  cpu_deployment_name: cpu-test
  name_for_registered_model: sample_model_single_label_classification
  batch_endpoint_name: batch-sl-class-jamg-nlp-dev
  online_endpoint_name: online-sl-class-jamg-nlp-dev
  cpu_instance_type: Standard_F8s_v2
  cpu_instance_count: 1
  apply_ort: "false"
  apply_deepspeed: "false"
  description: Creating Batch endpoint to deploy NLP model

jobs:
  create_batch_endpoint:
    type: command
    component: ../code/components/create_batch_endpoint.yaml
    compute: sample-managed-id-cluster
    inputs:
      endpoint_name: ${{parent.inputs.batch_endpoint_name}}
      description: ${{parent.inputs.description}}

  create_online_endpoint:
    type: command
    component: ../code/components/create_online_endpoint.yaml
    compute: sample-managed-id-cluster
    inputs:
      endpoint_name: ${{parent.inputs.online_endpoint_name}}
      description: ${{parent.inputs.description}}