# <component>
$schema: https://azuremlschemas.azureedge.net/latest/commandComponent.schema.json

# Reference documentation: https://learn.microsoft.com/en-us/azure/machine-learning/how-to-use-batch-endpoint?tabs=python

name: azureml_textclassificationsinglelabel_deploy
version: 0.0.1
display_name: Deploy model Batch endpoint
is_deterministic: True
type: command
description: Component to deploy finetuned model for single label classification task
inputs:
  endpoint_name:
    type: string
    optional: False
    description: Name of the batch endpoint.
  deployment_name:
    type: string
    optional: False
    description: Name of the deployment.
  model_path:
    type: string
    optional: False
    description: Path of model to be used or name of model in registry.
  compute:
    type: string
    optional: False
    description: Name of compute to be used for deployment
  instance_count:
    type: integer
    optional: True
    description: Name of compute to be used for deployment

code: ../create_deployment
environment: azureml://registries/azureml-preview/environments/finetune-acpt-pytorch-111-py38-cuda113-gpu/versions/0.0.5
resources:
  instance_count: 1
command: python create_batch_deployment.py --deployment_name ${{inputs.deployment_name}} --endpoint_name ${{inputs.endpoint_name}} --model_path ${{inputs.model_path}} --compute ${{inputs.compute}}  $[[--instance_count ${{inputs.instance_count}}]]